### ISSUE TITLE
listUsers returns 404

### ISSUE THREAD

**Issue by mwedgwood-rmn** [ekristen/docker-index#4]
Sorry, I suspect this is an implementation/configuration issue and probably not a bug, but ...

After setting up a registry with docker-index, listUsers (via the CLI) simply returns a 404.

```
$ docker-index listUsers my-registry.example.com
Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

My setup looks something like this (for testing, obviously don't want to use the same redis for the registry cache as for the index). This is a [fig](http://fig.sh) file.

```
registrycache:
  image: dockerfile/redis:latest
  command: redis-server /etc/redis/redis.conf --maxmemory-policy allkeys-lru
registry:
  build: ../../images/registry
  links:
    - registrycache
  environment:
    - SEARCH_BACKEND=sqlalchemy
    - CACHE_LRU_REDIS_HOST=registrycache
    - CACHE_LRU_REDIS_PORT=6379
    - LOGLEVEL=debug
    - INDEX_ENDPOINT=http://index:5100
proxy:
  build: ../../images/nginx
  ports:
    - "443:443"
  links:
    - registry
  volumes:
    - config/local/nginx/sites-enabled:/etc/nginx/sites-enabled
    - logs/nginx:/var/log/nginx
index:
  #  image: ekristen/docker-index:latest
  build: ../../images/docker-index
  ports:
    - "5100:5100"
  environment:
    - REGISTRIES=registry
  links:
    - registry
    - "registrycache:redis"
```
